NumCams=1;
columns=1;
rows=1;
print(NumCams,rows,columns)
print("\n")
NumCams=2;
columns=2;
rows=1;
print(NumCams,rows,columns)
print("\n")
NumCams=3;
columns=2;
rows=2;
print(NumCams,rows,columns)
NumCams=4;
columns=2;
rows=2;
print(NumCams,rows,columns)
print("\n")
NumCams=5;
columns=3;
rows=2;
print(NumCams,rows,columns)
NumCams=6;
columns=3;
rows=2;
print(NumCams,rows,columns)
print("\n")
NumCams=7;
columns=3;
rows=3;
print(NumCams,rows,columns)
NumCams=8;
columns=3;
rows=3;
print(NumCams,rows,columns)
NumCams=9;
columns=3;
rows=3;
print(NumCams,rows,columns)
print("\n")
NumCams=10;
columns=4;
rows=3;
print(NumCams,rows,columns)
NumCams=11;
columns=4;
rows=3;
print(NumCams,rows,columns)
NumCams=12;
columns=4;
rows=3;
print(NumCams,rows,columns)
print("\n")
NumCams=13;
columns=4;
rows=4;
print(NumCams,rows,columns)
NumCams=14;
columns=4;
rows=4;
print(NumCams,rows,columns)
NumCams=15;
columns=4;
rows=4;
print(NumCams,rows,columns)
NumCams=16;
columns=4;
rows=4;
print(NumCams,rows,columns)
print("\n")
NumCams=17;
columns=5;
rows=4;
print(NumCams,rows,columns)
NumCams=18;
columns=5;
rows=4;
print(NumCams,rows,columns)
NumCams=19;
columns=5;
rows=4;
print(NumCams,rows,columns)
NumCams=20;
columns=5;
rows=4;
print(NumCams,rows,columns)
print("\n")
NumCams=21;
columns=5;
rows=5;
print(NumCams,rows,columns)
NumCams=22;
columns=5;
rows=5;
print(NumCams,rows,columns)
NumCams=23;
columns=5;
rows=5;
print(NumCams,rows,columns)
NumCams=24;
columns=5;
rows=5;
print(NumCams,rows,columns)
NumCams=25;
columns=5;
rows=5;
print(NumCams,rows,columns)
print("\n")
NumCams=26;
columns=6;
rows=5;
print(NumCams,rows,columns)
NumCams=27;
columns=6;
rows=5;
print(NumCams,rows,columns)
NumCams=28;
columns=6;
rows=5;
print(NumCams,rows,columns)
NumCams=29;
columns=6;
rows=5;
print(NumCams,rows,columns)
NumCams=30;
columns=6;
rows=5;
print(NumCams,rows,columns)
print("\n")
NumCams=31;
columns=6;
rows=6;
print(NumCams,rows,columns)
NumCams=32;
columns=6;
rows=6;
print(NumCams,rows,columns)
NumCams=33;
columns=6;
rows=6;
print(NumCams,rows,columns)
NumCams=34;
columns=6;
rows=6;
print(NumCams,rows,columns)
NumCams=35;
columns=6;
rows=6;
print(NumCams,rows,columns)
NumCams=36;
columns=6;
rows=6;
print(NumCams,rows,columns)
